# Generated by Django 3.0.5 on 2020-04-21 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(default='0000000', max_length=500)),
                ('address1', models.CharField(default='0000000', max_length=500)),
                ('address2', models.CharField(default='0000000', max_length=500)),
                ('url', models.CharField(default='0000000', max_length=500)),
                ('name', models.CharField(default='0000000', max_length=50)),
                ('phone', models.CharField(default='0000000', max_length=50)),
            ],
        ),
    ]
