# Generated by Django 3.0.5 on 2020-04-21 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20200421_0306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='address',
        ),
        migrations.AddField(
            model_name='history',
            name='address1',
            field=models.CharField(default='0000000', max_length=500),
        ),
        migrations.AddField(
            model_name='history',
            name='address2',
            field=models.CharField(default='0000000', max_length=500),
        ),
        migrations.AddField(
            model_name='history',
            name='url',
            field=models.CharField(default='0000000', max_length=500),
        ),
        migrations.AlterField(
            model_name='history',
            name='image',
            field=models.CharField(default='0000000', max_length=500),
        ),
        migrations.AlterField(
            model_name='history',
            name='name',
            field=models.CharField(default='0000000', max_length=50),
        ),
        migrations.AlterField(
            model_name='history',
            name='phone',
            field=models.CharField(default='0000000', max_length=50),
        ),
    ]
